apiVersion: v1
data:
  branch:  demo-mq-v2-ha-gk
  host: github.com
  org: gkovan
  owner: gkovan
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops
  url: https://github.com/gkovan/multi-tenancy-gitops.git
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
  namespace: ci
